hydra:
  run:
    dir: .
  output_subdir: null 

data_name: 'alcock_multiband' # elasticc_1, plasticc, alcock, alcock_multiband
subsets: ['train', 'val', 'test'] # 'train', 
list_folds: [0] #, 3, 4]
num_cores: 20
samples_per_shard: 1000

norm_name: 'minmax_by_obj'
input_type: '2grid'  # 'grid' # 'overlay'
use_err: false

fig_params: {
    figsize: [2.56, 2.56], # [2.56, 2.56],
    fmt: '-o', #-o
    markersize: 1., # 2.5,
    linewidth: 1., # 1.2,
    colors: {
      #0: '#00FF70',
      #1: '#70FF00',
      #2: '#FF0070',
      #3: '#FF7000',
      #4: '#0070FF',
      #5: '#7000FF',
      0: '#00FF7F',  # Cercano al verde
      1: '#7FFF00',  # Cercano al verde
      2: '#FF007F',  # Cercano al rojo
      3: '#FF7F00',  # Cercano al rojo
      4: '#007FFF',  # Cercano al azul
      5: '#7F00FF',   # Cercano al azul
    },
    alpha: 0.5,
    ylim: [-0.05, 1.05],
}

extra_plasticc: {
  'only_test': {
    'use': False,
    'path_partition': 'data/lightcurves/plasticc/partitions/test/stratified_5fold_splits_1391921_objs.parquet',
  },
  'augmented_data': {
    'use': False,
    'path_data': 'data/lightcurves/plasticc/augmented_data/oversampling_30000_class',
  }
}

