
plasticc:
  path_data: 'data/lightcurves/plasticc/raw'
  path_partition: 'data/lightcurves/plasticc/partitions'
  dict_columns: {
    snid: 'object_id',
    mjd: 'mjd',
    flux: 'flux',
    flux_err: 'flux_err',
    photflag: 'detected',
    band: 'passband',
    label: 'target'
  }
  all_bands: {
    0: 'u', 
    1: 'g', 
    2: 'r', 
    3: 'i', 
    4: 'z', 
    5: 'Y'
    }
  dict_mapping_real_classes: {
    6: 'Single u-lens',
    15: 'TDE',
    16: 'Eclip. Binary',
    42: 'SNII',
    52: 'SNIax',
    53: 'Mira',
    62: 'SNIbc',
    64: 'Kilonova',
    65: 'M-dwarf',
    67: 'SNIa-91bg',
    88: 'AGN',
    90: 'SNIa',
    92: 'RR lyrae',
    95: 'SLSN-I',
    #991: Others,
    #992: Others,
    #993: Others,
    #994: Others, # Si lo considero, manualmente deberia cambiarlo en get_plasticc
  }
  dict_mapping_classes: {
    RR lyrae: 0,
    AGN: 1,
    SNII: 2,
    SNIa: 3,
    M-dwarf: 4,
    Eclip. Binary: 5,
    SNIa-91bg: 6,
    SLSN-I: 7,
    SNIbc: 8,
    TDE: 9,
    SNIax: 10,
    Single u-lens: 11,
    Kilonova: 12,
    Mira: 13,
  }

elasticc_1:
  data_dir: 'data/lightcurves/elasticc_1/raw'
  path_partition: 'data/lightcurves/elasticc_1/ATAT_partition/partitions_v1.parquet'
  dict_columns: {
    snid: 'SNID',
    mjd: 'MJD',
    flux: 'FLUXCAL',
    flux_err: 'FLUXCALERR',
    band: 'BAND', 
    label: 'label',
  }
  all_bands: {
    u: 0, 
    g: 1, 
    r: 2, 
    i: 3, 
    z: 4, 
    Y: 5,
    }
  dict_mapping_real_classes: {
    AGN: 'AGN',
    CART: 'CART',
    Cepheid: 'Cepheid',
    d-Sct: 'Delta Scuti',
    dwarf-nova: 'Dwarf Novae',
    EB: 'EB',
    ILOT: 'ILOT',
    KN_B19: 'KN',
    KN_K17: 'KN',
    Mdwarf-flare: 'M-dwarf Flare',
    PISN: 'PISN',
    RRL: 'RR Lyrae',
    SLSN-I+host: 'SLSN',
    SLSN-I_no_host: 'SLSN',
    SNIa-91bg: '91bg',
    SNIa-SALT2: 'Ia',
    SNIax: 'Iax',
    SNIb+HostXT_V19: 'Ib/c',
    SNIb-Templates: 'Ib/c',
    SNIc+HostXT_V19: 'Ib/c',
    SNIc-Templates: 'Ib/c',
    SNIcBL+HostXT_V19: 'Ib/c',
    SNII+HostXT_V19: 'II',
    SNII-NMF: 'II',
    SNII-Templates: 'II',
    SNIIb+HostXT_V19: 'SN-like/Other',
    SNIIn+HostXT_V19: 'II',
    SNIIn-MOSFIT: 'II',
    TDE: 'TDE',
    uLens-Binary: 'uLens',
    uLens-Single-GenLens: 'uLens',
    uLens-Single_PyLIMA: 'uLens'
  }
  dict_mapping_classes: {
    91bg: 0,
    AGN: 1,
    CART: 2,
    Cepheid: 3,
    Delta Scuti: 4,
    Dwarf Novae: 5,
    EB: 6,
    II: 7,
    ILOT: 8,
    Ia: 9,
    Iax: 10,
    Ib/c: 11,
    KN: 12,
    M-dwarf Flare: 13,
    PISN: 14,
    RR Lyrae: 15,
    SLSN: 16,
    SN-like/Other: 17,
    TDE: 18,
    uLens: 19
  }
  col_metadata: [
    'HOSTGAL2_ELLIPTICITY',
    'HOSTGAL2_MAG_Y',
    'HOSTGAL2_MAG_g',
    'HOSTGAL2_MAG_i',
    'HOSTGAL2_MAG_r',
    'HOSTGAL2_MAG_u',
    'HOSTGAL2_MAG_z',
    'HOSTGAL2_MAGERR_Y',
    'HOSTGAL2_MAGERR_g',
    'HOSTGAL2_MAGERR_i',
    'HOSTGAL2_MAGERR_r',
    'HOSTGAL2_MAGERR_u',
    'HOSTGAL2_MAGERR_z',
    'HOSTGAL2_SNSEP',
    'HOSTGAL2_SQRADIUS',
    'HOSTGAL2_PHOTOZ',
    'HOSTGAL2_PHOTOZ_ERR',
    'HOSTGAL2_ZPHOT_Q000',
    'HOSTGAL2_ZPHOT_Q010',
    'HOSTGAL2_ZPHOT_Q020',
    'HOSTGAL2_ZPHOT_Q030',
    'HOSTGAL2_ZPHOT_Q040',
    'HOSTGAL2_ZPHOT_Q050',
    'HOSTGAL2_ZPHOT_Q060',
    'HOSTGAL2_ZPHOT_Q070',
    'HOSTGAL2_ZPHOT_Q080',
    'HOSTGAL2_ZPHOT_Q090',
    'HOSTGAL2_ZPHOT_Q100',
    'HOSTGAL2_SPECZ',
    'HOSTGAL2_SPECZ_ERR',
    'HOSTGAL_ELLIPTICITY',
    'HOSTGAL_MAG_Y',
    'HOSTGAL_MAG_g',
    'HOSTGAL_MAG_i',
    'HOSTGAL_MAG_r',
    'HOSTGAL_MAG_u',
    'HOSTGAL_MAG_z',
    'HOSTGAL_MAGERR_Y',
    'HOSTGAL_MAGERR_g',
    'HOSTGAL_MAGERR_i',
    'HOSTGAL_MAGERR_r',
    'HOSTGAL_MAGERR_u',
    'HOSTGAL_MAGERR_z',
    'HOSTGAL_SNSEP',
    'HOSTGAL_SQRADIUS',
    'HOSTGAL_PHOTOZ',
    'HOSTGAL_PHOTOZ_ERR',
    'HOSTGAL_ZPHOT_Q000',
    'HOSTGAL_ZPHOT_Q010',
    'HOSTGAL_ZPHOT_Q020',
    'HOSTGAL_ZPHOT_Q030',
    'HOSTGAL_ZPHOT_Q040',
    'HOSTGAL_ZPHOT_Q050',
    'HOSTGAL_ZPHOT_Q060',
    'HOSTGAL_ZPHOT_Q070',
    'HOSTGAL_ZPHOT_Q080',
    'HOSTGAL_ZPHOT_Q090',
    'HOSTGAL_ZPHOT_Q100',
    'HOSTGAL_SPECZ',
    'HOSTGAL_SPECZ_ERR',
    'MWEBV',
    'MWEBV_ERR',
    'REDSHIFT_HELIO',
    'REDSHIFT_HELIO_ERR'
  ]

alcock:
  data_dir: 'data/lightcurves/alcock/raw'
  path_partition: 'data/lightcurves/alcock/ASTROMER_partition/partitions_v1.parquet'
  dict_columns: {
    snid: 'lcid',
    mjd: 'mjd',
    flux: 'mag',
    flux_err: 'err',
    band: 'band',
    label: 'label',
  }
  all_bands: {
    R: 1, 
    }
  dict_mapping_classes: {
    Cep_0: 0,  # Cepheid Type I
    Cep_1: 1,  # Cepheid Type II
    EC: 2,     # Eclipsing Binary
    LPV: 3,    # Long Period Variable
    RRab: 4,   # RR Lyrae Type AB
    RRc: 5,    # RR Lyrae Type C
  }

alcock_multiband:
  data_dir: 'data/lightcurves/alcock/raw'
  path_partition: 'data/lightcurves/alcock/ASTROMER_partition/partitions_v1.parquet'
  dict_columns: {
    snid: 'lcid',
    mjd: 'mjd',
    flux: 'mag',
    flux_err: 'err',
    band: 'band',
    label: 'label',
  }
  all_bands: {
    B: 0, 
    R: 1, 
    }
  dict_mapping_classes: {
    Cep_0: 0,  # Cepheid Type I
    Cep_1: 1,  # Cepheid Type II
    EC: 2,     # Eclipsing Binary
    LPV: 3,    # Long Period Variable
    RRab: 4,   # RR Lyrae Type AB
    RRc: 5,    # RR Lyrae Type C
  }

ogle:
  path_data: 'data/lightcurves/astromer'
  list_spc: [20] #, 50, 100, 500, 'all'] 
  dict_columns: {
    snid: 'lcid',
    mjd: 'mjd',
    flux: 'flux',
    flux_err: 'flux_err',
    label: 'label',
  }
  all_bands: false
  dict_mapping_classes: {
    EC: 0,      # Eclipsing Binary
    ED: 1,      # Detached Binary (often used synonymously with EC in some contexts)
    ESD: 2,     # Semi-Detached Binary
    Mira: 3,    # Mira Variable
    OSARG: 4,   # Small Amplitude Red Giants (often treated as semi-regular or less variable than Mira)
    RRab: 5,    # RR Lyrae Type AB
    RRc: 6,     # RR Lyrae Type C
    SRV: 7,     # Semi-Regular Variable
    cep: 8,     # Cepheid Variables
    dsct: 9,    # Delta Scuti
    }

atlas:
  path_data: 'data/lightcurves/astromer'
  list_spc: [20] #, 50, 100, 500, 'all']
  dict_columns: {
    snid: 'lcid',
    mjd: 'mjd',
    flux: 'flux',
    flux_err: 'flux_err',
    label: 'label',
  }
  all_bands: false
  dict_mapping_classes: {
    CB: 0,      # Close Binaries
    DB: 1,      # Detached Binary
    Mira: 2,    # Mira Variable
    Other: 3,   # Other categories not specified here
    Pulse: 4,   # Pulsating stars (General category)
  }

macho:
  path_data: 'data/lightcurves/astromer'
  list_spc: ['all']
  dict_columns: {
    snid: 'lcid',
    mjd: 'mjd',
    flux: 'flux',
    flux_err: 'flux_err',
    label: 'label',
  }
  all_bands: false
  dict_mapping_classes: false