hydra:
  run:
    dir: .
  output_subdir: null 

ft_classification:
  results_dir: 'results'
  exp_description: ''

  model_name: 'swinv2'
  checkpoint: {
    'use': false,
    'exp_name': 'ft_classification/elasticc_1/testing',
    'run_name': '2024-08-31_01-39-33',
    'results_dir': 'results',
  } 
  pretrained_model: {
    'use': true,
    'path': "microsoft/swinv2-tiny-patch4-window16-256",
  }
  list_folds: [0] #, 1, 2, 3, 4]
  
  # General Configuration
  debug: false

  # Loaders Configuration
  loader:
    path_data: 'data/lightcurves/elasticc_1'
    spc: null
    num_workers: 15
    use_png: false

  # Training Configuration
  training:
    lr: 5.0e-5
    patience: 10
    num_epochs: 10000
    batch_size: 64
    use_weighted_sampling: false
    monitor: 'f1/val'
    cache_enabled: true

    classifier: {
      use: true,
      only_train_classifier: false,
    }

    use_metadata: false
  
  imgs_params:
    norm_name: 'minmax_by_obj'
    input_type: '6grid'  # '2grid', 'overlay', '6grid' 
    use_err: false

    fig_params: {
        figsize: [2.56, 2.56], # [2.56, 2.56],
        fmt: '-o', #-o
        markersize: 2.0, # 2.5,
        linewidth: 1.0, # 1.2,
        colors: {
          0: '#00FF7F',  # Cercano al verde
          1: '#7FFF00',  # Cercano al verde
          2: '#FF007F',  # Cercano al rojo
          3: '#FF7F00',  # Cercano al rojo
          4: '#007FFF',  # Cercano al azul
          5: '#7F00FF',   # Cercano al azul
        },
        alpha: 0.5,
        xlim: [-0.05, 1.05],
        ylim: [-0.05, 1.05],
    }
